### PR TITLE
Added Key Value Observing support for currentColor.

### PR DESCRIPTION
**Pull request by dimensionerror**
I added willChangeValueForKey and didChangeValueForKey method calls to wrap changes to the currentColor property so that outside classes can use KVO to monitor the color.

### CODE REVIEW

**Comment by justinmeiners** [comment]
I am interested in this change, however I would like to avoid an additional file for the string category. Is it possible to add KVO without that category?

**Comment by dimensionerror** [comment]
Yes, it is. I removed the category but have not tested the changes.

**Comment by justinmeiners** [comment]
If you were to create a new pull request, or just send me the relevant code I would be happy to integrate and test it for you. I am familiar with KVO just not how to implement it for properties.

**Comment by justinmeiners** [comment]
Oh thank you! I just saw you changed that. I will go ahead and integrate this later today.

**Pull request merged**
